CREATE TABLE `candidate_reels` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tiktokId` varchar(100) NOT NULL,
	`tiktokUrl` varchar(500) NOT NULL,
	`authorUsername` varchar(100),
	`authorName` varchar(255),
	`description` text,
	`coverUrl` varchar(500),
	`videoUrl` varchar(500),
	`duration` int,
	`likes` int NOT NULL DEFAULT 0,
	`comments` int NOT NULL DEFAULT 0,
	`shares` int NOT NULL DEFAULT 0,
	`views` int NOT NULL DEFAULT 0,
	`hashtags` json,
	`searchQuery` varchar(255) NOT NULL,
	`sectorSlug` varchar(100) NOT NULL,
	`publishTime` timestamp,
	`predictedViralScore` int,
	`predictedViralReason` text,
	`status` enum('pending','labeled','skipped') NOT NULL DEFAULT 'pending',
	`foundAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `candidate_reels_id` PRIMARY KEY(`id`),
	CONSTRAINT `candidate_reels_tiktokId_unique` UNIQUE(`tiktokId`)
);
--> statement-breakpoint
CREATE TABLE `labeled_reels` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tiktokId` varchar(100) NOT NULL,
	`tiktokUrl` varchar(500) NOT NULL,
	`authorUsername` varchar(100),
	`description` text,
	`coverUrl` varchar(500),
	`duration` int,
	`likes` int NOT NULL DEFAULT 0,
	`comments` int NOT NULL DEFAULT 0,
	`shares` int NOT NULL DEFAULT 0,
	`views` int NOT NULL DEFAULT 0,
	`likeToViewRatio` decimal(10,6),
	`commentToViewRatio` decimal(10,6),
	`shareToViewRatio` decimal(10,6),
	`engagementRate` decimal(10,6),
	`hashtags` json,
	`hasHook` boolean,
	`hookType` varchar(100),
	`contentType` varchar(100),
	`hasCTA` boolean,
	`hasTextOverlay` boolean,
	`hasTrendingSound` boolean,
	`sectorSlug` varchar(100) NOT NULL,
	`isViral` boolean NOT NULL,
	`labelNotes` text,
	`labeledBy` int NOT NULL,
	`labeledAt` timestamp NOT NULL DEFAULT (now()),
	`searchQuery` varchar(255),
	`publishTime` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `labeled_reels_id` PRIMARY KEY(`id`),
	CONSTRAINT `labeled_reels_tiktokId_unique` UNIQUE(`tiktokId`)
);
--> statement-breakpoint
CREATE TABLE `virality_patterns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sectorSlug` varchar(100) NOT NULL,
	`avgLikeToViewRatio` decimal(10,6),
	`avgEngagementRate` decimal(10,6),
	`minLikesThreshold` int,
	`optimalDurationMin` int,
	`optimalDurationMax` int,
	`commonHookTypes` json,
	`commonContentTypes` json,
	`topHashtags` json,
	`likeWeight` decimal(5,3) DEFAULT '0.3',
	`commentWeight` decimal(5,3) DEFAULT '0.2',
	`shareWeight` decimal(5,3) DEFAULT '0.3',
	`viewWeight` decimal(5,3) DEFAULT '0.2',
	`totalLabeledReels` int NOT NULL DEFAULT 0,
	`viralReelsCount` int NOT NULL DEFAULT 0,
	`notViralReelsCount` int NOT NULL DEFAULT 0,
	`accuracy` decimal(5,2),
	`lastTrainedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `virality_patterns_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `labeled_reels` ADD CONSTRAINT `labeled_reels_labeledBy_users_id_fk` FOREIGN KEY (`labeledBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;